# ---------------------------------------------------------------------------
# Dockerfile: Dockerfile.frontend
# Description: Builds the Node.js frontend environment.
#              Used for serving the City Dashboard and running the Driver PWA.
# ---------------------------------------------------------------------------

FROM node:18-slim

WORKDIR /app

# Copy the rest of the application
COPY . .

# Make scripts executable
RUN chmod +x docker/*.sh

CMD ["bash", "docker/start_frontends.sh"]